<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link rel="stylesheet" href="css/styles.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.min.js" integrity="sha384-RuyvpeZCxMJCqVUGFI0Do1mQrods/hhxYlcVfGPOfQtPJh0JCw12tUAZ/Mv10S7D" crossorigin="anonymous"></script>
</head>
  <body>
    <ul>
        <li><a href="index.html">Home</a></li>
        <li><a href="details.html">Eastern Box Turtle</a></li>
        <li><a href="about.html">About</a></li>
    </ul>
    <h1 style="text-align:center">Hello, welcome to my gallery of turtles and tortoises!</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
    <div class="row">
        <div class="col-sm">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <img src="images\A._gigantea_Aldabra_Giant_Tortoise.jpg" alt="Aldabra Giant Tortoise" style="width:100%">
                    <p>This is a Aldabra giant tortoise, a species of tortoise. They are only found on the island nation of the Republic of Seychelles.</p> 
                    <a href="details.html" class="btn btn-info">Learn more</a>
                </div>
            </div>
        </div>
        <div class="col-sm">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <img src="images\Chelonia_mydas_is_going_for_the_air_edit.jpg" alt="Green Sea Turtle" style="width:100%">
                    <p>This is a green sea turtle, a large species of sea turtle. It is native to the tropical and subtropical, mainly in the Atlantic and Pacific Oceans, but can also be found in the Indian Ocean.</p> 
                    <a href="details.html" class="btn btn-info">Learn more</a>
                </div>
            </div>
        </div>
        <div class="col-sm">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <img src="images\Eastern_box_turtle_in_the_grass.jpg" alt="Eastern Box Turtle" style="width:100%">
                    <p>This is a eastern box turtle, a subspecies of common box turtles. They are found in the Eastern United States.</p> 
                    <a href="details.html" class="btn btn-info">Learn more</a>
                </div>
            </div> 
        </div>
        <div class="col-sm">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <img src="images\Florida_Box_Turtle.jpg" alt="Aldabra Giant Tortoise" style="width:100%">
                    <p>This is a Florida box turtle, a subspecies of common box turtles. They are found in Florida and the southeastern parts of Georgia.</p> 
                    <a href="details.html" class="btn btn-info">Learn more</a>
                </div>
            </div>
        </div>
        <div class="col-sm">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <img src="images\Leatherback_sea_turtle.jpg" alt="Green Sea Turtle" style="width:100%">
                    <p>This is a leatherback sea turtle, the only living member of the its genus of sea turtles. They can be found in any open ocean, so they are a global animal.</p> 
                    <a href="details.html" class="btn btn-info">Learn more</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
